/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElEMe: typeof import('element-plus/es').ElEMe
  const ElMessa: typeof import('element-plus/es').ElMessa
  const ElMessage: typeof import('element-plus/es').ElMessage
}
